/**
 * Diablo II Constants, Lookups & Item Database
 */

const CLASSES = ['Amazon', 'Sorceress', 'Necromancer', 'Paladin', 'Barbarian', 'Druid', 'Assassin'];

const CLASS_SKILLS = {
  // Amazon (Class ID 0)
  0: [
    { id: 6, name: 'Magic Arrow', tree: 'Bow and Crossbow' },
    { id: 7, name: 'Fire Arrow', tree: 'Bow and Crossbow' },
    { id: 11, name: 'Cold Arrow', tree: 'Bow and Crossbow' },
    { id: 12, name: 'Multiple Shot', tree: 'Bow and Crossbow' },
    { id: 16, name: 'Exploding Arrow', tree: 'Bow and Crossbow' },
    { id: 21, name: 'Ice Arrow', tree: 'Bow and Crossbow' },
    { id: 22, name: 'Guided Arrow', tree: 'Bow and Crossbow' },
    { id: 26, name: 'Strafe', tree: 'Bow and Crossbow' },
    { id: 27, name: 'Immolation Arrow', tree: 'Bow and Crossbow' },
    { id: 31, name: 'Freezing Arrow', tree: 'Bow and Crossbow' },

    { id: 8, name: 'Inner Sight', tree: 'Passive and Magic' },
    { id: 9, name: 'Critical Strike', tree: 'Passive and Magic' },
    { id: 13, name: 'Dodge', tree: 'Passive and Magic' },
    { id: 14, name: 'Slow Missiles', tree: 'Passive and Magic' },
    { id: 18, name: 'Avoid', tree: 'Passive and Magic' },
    { id: 19, name: 'Penetrate', tree: 'Passive and Magic' },
    { id: 23, name: 'Decoy', tree: 'Passive and Magic' },
    { id: 24, name: 'Evade', tree: 'Passive and Magic' },
    { id: 28, name: 'Valkyrie', tree: 'Passive and Magic' },
    { id: 29, name: 'Pierce', tree: 'Passive and Magic' },

    { id: 10, name: 'Jab', tree: 'Javelin and Spear' },
    { id: 15, name: 'Power Strike', tree: 'Javelin and Spear' },
    { id: 17, name: 'Poison Javelin', tree: 'Javelin and Spear' },
    { id: 20, name: 'Impale', tree: 'Javelin and Spear' },
    { id: 25, name: 'Lightning Bolt', tree: 'Javelin and Spear' },
    { id: 30, name: 'Charged Strike', tree: 'Javelin and Spear' },
    { id: 32, name: 'Plague Javelin', tree: 'Javelin and Spear' },
    { id: 33, name: 'Fend', tree: 'Javelin and Spear' },
    { id: 34, name: 'Lightning Strike', tree: 'Javelin and Spear' },
    { id: 35, name: 'Lightning Fury', tree: 'Javelin and Spear' }
  ],

  // Sorceress (Class ID 1)
  1: [
    { id: 36, name: 'Fire Bolt', tree: 'Fire Spells' },
    { id: 37, name: 'Warmth', tree: 'Fire Spells' },
    { id: 38, name: 'Charged Bolt', tree: 'Lightning Spells' },
    { id: 39, name: 'Ice Bolt', tree: 'Cold Spells' },
    { id: 40, name: 'Frozen Armor', tree: 'Cold Spells' },
    { id: 41, name: 'Inferno', tree: 'Fire Spells' },
    { id: 42, name: 'Static Field', tree: 'Lightning Spells' },
    { id: 43, name: 'Telekinesis', tree: 'Lightning Spells' },
    { id: 44, name: 'Frost Nova', tree: 'Cold Spells' },
    { id: 45, name: 'Ice Blast', tree: 'Cold Spells' },
    { id: 46, name: 'Blaze', tree: 'Fire Spells' },
    { id: 47, name: 'Fire Ball', tree: 'Fire Spells' },
    { id: 48, name: 'Nova', tree: 'Lightning Spells' },
    { id: 49, name: 'Lightning', tree: 'Lightning Spells' },
    { id: 50, name: 'Shiver Armor', tree: 'Cold Spells' },
    { id: 51, name: 'Fire Wall', tree: 'Fire Spells' },
    { id: 52, name: 'Enchant', tree: 'Fire Spells' },
    { id: 53, name: 'Chain Lightning', tree: 'Lightning Spells' },
    { id: 54, name: 'Teleport', tree: 'Lightning Spells' },
    { id: 55, name: 'Glacial Spike', tree: 'Cold Spells' },
    { id: 56, name: 'Meteor', tree: 'Fire Spells' },
    { id: 57, name: 'Thunder Storm', tree: 'Lightning Spells' },
    { id: 58, name: 'Energy Shield', tree: 'Lightning Spells' },
    { id: 59, name: 'Blizzard', tree: 'Cold Spells' },
    { id: 60, name: 'Chilling Armor', tree: 'Cold Spells' },
    { id: 61, name: 'Fire Mastery', tree: 'Fire Spells' },
    { id: 62, name: 'Hydra', tree: 'Fire Spells' },
    { id: 63, name: 'Lightning Mastery', tree: 'Lightning Spells' },
    { id: 64, name: 'Frozen Orb', tree: 'Cold Spells' },
    { id: 65, name: 'Cold Mastery', tree: 'Cold Spells' },
  ],

  // Necromancer (Class ID 2)
  2: [
    { id: 66, name: 'Amplify Damage', tree: 'Curses' },
    { id: 67, name: 'Teeth', tree: 'Poison and Bone' },
    { id: 68, name: 'Bone Armor', tree: 'Poison and Bone' },
    { id: 69, name: 'Skeleton Mastery', tree: 'Summoning' },
    { id: 70, name: 'Raise Skeleton', tree: 'Summoning' },
    { id: 71, name: 'Dim Vision', tree: 'Curses' },
    { id: 72, name: 'Weaken', tree: 'Curses' },
    { id: 73, name: 'Poison Dagger', tree: 'Poison and Bone' },
    { id: 74, name: 'Corpse Explosion', tree: 'Poison and Bone' },
    { id: 75, name: 'Clay Golem', tree: 'Summoning' },
    { id: 76, name: 'Iron Maiden', tree: 'Curses' },
    { id: 77, name: 'Terror', tree: 'Curses' },
    { id: 78, name: 'Bone Wall', tree: 'Poison and Bone' },
    { id: 79, name: 'Golem Mastery', tree: 'Summoning' },
    { id: 80, name: 'Raise Skeletal Mage', tree: 'Summoning' },
    { id: 81, name: 'Confuse', tree: 'Curses' },
    { id: 82, name: 'Life Tap', tree: 'Curses' },
    { id: 83, name: 'Poison Explosion', tree: 'Poison and Bone' },
    { id: 84, name: 'Bone Spear', tree: 'Poison and Bone' },
    { id: 85, name: 'Blood Golem', tree: 'Summoning' },
    { id: 86, name: 'Attract', tree: 'Curses' },
    { id: 87, name: 'Decrepify', tree: 'Curses' },
    { id: 88, name: 'Bone Prison', tree: 'Poison and Bone' },
    { id: 89, name: 'Summon Resist', tree: 'Summoning' },
    { id: 90, name: 'Iron Golem', tree: 'Summoning' },
    { id: 91, name: 'Lower Resist', tree: 'Curses' },
    { id: 92, name: 'Poison Nova', tree: 'Poison and Bone' },
    { id: 93, name: 'Bone Spirit', tree: 'Poison and Bone' },
    { id: 94, name: 'Fire Golem', tree: 'Summoning' },
    { id: 95, name: 'Revive', tree: 'Summoning' },
  ],

  // Paladin (Class ID 3)
  3: [
    { id: 96, name: 'Sacrifice', tree: 'Combat Skills' },
    { id: 97, name: 'Smite', tree: 'Combat Skills' },
    { id: 98, name: 'Might', tree: 'Offensive Auras' },
    { id: 99, name: 'Prayer', tree: 'Defensive Auras' },
    { id: 100, name: 'Resist Fire', tree: 'Defensive Auras' },
    { id: 101, name: 'Holy Bolt', tree: 'Combat Skills' },
    { id: 102, name: 'Holy Fire', tree: 'Offensive Auras' },
    { id: 103, name: 'Thorns', tree: 'Offensive Auras' },
    { id: 104, name: 'Defiance', tree: 'Defensive Auras' },
    { id: 105, name: 'Resist Cold', tree: 'Defensive Auras' },
    { id: 106, name: 'Zeal', tree: 'Combat Skills' },
    { id: 107, name: 'Charge', tree: 'Combat Skills' },
    { id: 108, name: 'Blessed Aim', tree: 'Offensive Auras' },
    { id: 109, name: 'Cleansing', tree: 'Defensive Auras' },
    { id: 110, name: 'Resist Lightning', tree: 'Defensive Auras' },
    { id: 111, name: 'Vengeance', tree: 'Combat Skills' },
    { id: 112, name: 'Blessed Hammer', tree: 'Combat Skills' },
    { id: 113, name: 'Concentration', tree: 'Offensive Auras' },
    { id: 114, name: 'Holy Freeze', tree: 'Offensive Auras' },
    { id: 115, name: 'Vigor', tree: 'Defensive Auras' },
    { id: 116, name: 'Conversion', tree: 'Combat Skills' },
    { id: 117, name: 'Holy Shield', tree: 'Combat Skills' },
    { id: 118, name: 'Holy Shock', tree: 'Offensive Auras' },
    { id: 119, name: 'Sanctuary', tree: 'Offensive Auras' },
    { id: 120, name: 'Meditation', tree: 'Defensive Auras' },
    { id: 121, name: 'Fist of the Heavens', tree: 'Combat Skills' },
    { id: 122, name: 'Fanaticism', tree: 'Offensive Auras' },
    { id: 123, name: 'Conviction', tree: 'Offensive Auras' },
    { id: 124, name: 'Redemption', tree: 'Defensive Auras' },
    { id: 125, name: 'Salvation', tree: 'Defensive Auras' },
  ],

  // Barbarian (Class ID 4)
  4: [
    { id: 126, name: 'Bash', tree: 'Combat Skills' },
    { id: 127, name: 'Sword Mastery', tree: 'Combat Masteries' },
    { id: 128, name: 'Axe Mastery', tree: 'Combat Masteries' },
    { id: 129, name: 'Mace Mastery', tree: 'Combat Masteries' },
    { id: 130, name: 'Howl', tree: 'Warcries' },
    { id: 131, name: 'Find Potion', tree: 'Warcries' },
    { id: 132, name: 'Leap', tree: 'Combat Skills' },
    { id: 133, name: 'Double Swing', tree: 'Combat Skills' },
    { id: 134, name: 'Polearm Mastery', tree: 'Combat Masteries' },
    { id: 135, name: 'Throwing Mastery', tree: 'Combat Masteries' },
    { id: 136, name: 'Spear Mastery', tree: 'Combat Masteries' },
    { id: 137, name: 'Taunt', tree: 'Warcries' },
    { id: 138, name: 'Shout', tree: 'Warcries' },
    { id: 139, name: 'Stun', tree: 'Combat Skills' },
    { id: 140, name: 'Double Throw', tree: 'Combat Skills' },
    { id: 141, name: 'Increased Stamina', tree: 'Combat Masteries' },
    { id: 142, name: 'Find Item', tree: 'Warcries' },
    { id: 143, name: 'Leap Attack', tree: 'Combat Skills' },
    { id: 144, name: 'Concentrate', tree: 'Combat Skills' },
    { id: 145, name: 'Iron Skin', tree: 'Combat Masteries' },
    { id: 146, name: 'Battle Cry', tree: 'Warcries' },
    { id: 147, name: 'Frenzy', tree: 'Combat Skills' },
    { id: 148, name: 'Increased Speed', tree: 'Combat Masteries' },
    { id: 149, name: 'Battle Orders', tree: 'Warcries' },
    { id: 150, name: 'Grim Ward', tree: 'Warcries' },
    { id: 151, name: 'Whirlwind', tree: 'Combat Skills' },
    { id: 152, name: 'Berserk', tree: 'Combat Skills' },
    { id: 153, name: 'Natural Resistance', tree: 'Combat Masteries' },
    { id: 154, name: 'War Cry', tree: 'Warcries' },
    { id: 155, name: 'Battle Command', tree: 'Warcries' },
  ],

  // Druid (Class ID 5)
  5: [
    { id: 221, name: 'Raven', tree: 'Summoning' },
    { id: 222, name: 'Poison Creeper', tree: 'Summoning' },
    { id: 223, name: 'Werewolf', tree: 'Shape Shifting' },
    { id: 224, name: 'Lycanthropy', tree: 'Shape Shifting' },
    { id: 225, name: 'Firestorm', tree: 'Elemental' },
    { id: 226, name: 'Oak Sage', tree: 'Summoning' },
    { id: 227, name: 'Summon Spirit Wolf', tree: 'Summoning' },
    { id: 228, name: 'Werebear', tree: 'Shape Shifting' },
    { id: 229, name: 'Molten Boulder', tree: 'Elemental' },
    { id: 230, name: 'Arctic Blast', tree: 'Elemental' },
    { id: 231, name: 'Cycle of Life', tree: 'Summoning' },
    { id: 232, name: 'Feral Rage', tree: 'Shape Shifting' },
    { id: 233, name: 'Maul', tree: 'Shape Shifting' },
    { id: 234, name: 'Eruption', tree: 'Elemental' },
    { id: 235, name: 'Cyclone Armor', tree: 'Elemental' },
    { id: 236, name: 'Heart of Wolverine', tree: 'Summoning' },
    { id: 237, name: 'Summon Fenris', tree: 'Summoning' },
    { id: 238, name: 'Rabies', tree: 'Shape Shifting' },
    { id: 239, name: 'Fire Claws', tree: 'Shape Shifting' },
    { id: 240, name: 'Twister', tree: 'Elemental' },
    { id: 241, name: 'Vines', tree: 'Summoning' },
    { id: 242, name: 'Hunger', tree: 'Shape Shifting' },
    { id: 243, name: 'Shock Wave', tree: 'Shape Shifting' },
    { id: 244, name: 'Volcano', tree: 'Elemental' },
    { id: 245, name: 'Tornado', tree: 'Elemental' },
    { id: 246, name: 'Spirit of Barbs', tree: 'Summoning' },
    { id: 247, name: 'Summon Grizzly', tree: 'Summoning' },
    { id: 248, name: 'Fury', tree: 'Shape Shifting' },
    { id: 249, name: 'Armageddon', tree: 'Elemental' },
    { id: 250, name: 'Hurricane', tree: 'Elemental' },
  ],

  // Assassin (Class ID 6)
  6: [
    { id: 251, name: 'Fire Blast', tree: 'Traps' },
    { id: 252, name: 'Claw Mastery', tree: 'Shadow Disciplines' },
    { id: 253, name: 'Psychic Hammer', tree: 'Shadow Disciplines' },
    { id: 254, name: 'Tiger Strike', tree: 'Martial Arts' },
    { id: 255, name: 'Dragon Talon', tree: 'Martial Arts' },
    { id: 256, name: 'Shock Web', tree: 'Traps' },
    { id: 257, name: 'Blade Sentinel', tree: 'Traps' },
    { id: 258, name: 'Burst of Speed', tree: 'Shadow Disciplines' },
    { id: 259, name: 'Fists of Fire', tree: 'Martial Arts' },
    { id: 260, name: 'Dragon Claw', tree: 'Martial Arts' },
    { id: 261, name: 'Charged Bolt Sentry', tree: 'Traps' },
    { id: 262, name: 'Wake of Fire Sentry', tree: 'Traps' },
    { id: 263, name: 'Weapon Block', tree: 'Shadow Disciplines' },
    { id: 264, name: 'Cloak of Shadows', tree: 'Shadow Disciplines' },
    { id: 265, name: 'Cobra Strike', tree: 'Martial Arts' },
    { id: 266, name: 'Blade Fury', tree: 'Traps' },
    { id: 267, name: 'Fade', tree: 'Shadow Disciplines' },
    { id: 268, name: 'Shadow Warrior', tree: 'Shadow Disciplines' },
    { id: 269, name: 'Claws of Thunder', tree: 'Martial Arts' },
    { id: 270, name: 'Dragon Tail', tree: 'Martial Arts' },
    { id: 271, name: 'Lightning Sentry', tree: 'Traps' },
    { id: 272, name: 'Inferno Sentry', tree: 'Traps' },
    { id: 273, name: 'Mind Blast', tree: 'Shadow Disciplines' },
    { id: 274, name: 'Blades of Ice', tree: 'Martial Arts' },
    { id: 275, name: 'Dragon Flight', tree: 'Martial Arts' },
    { id: 276, name: 'Death Sentry', tree: 'Traps' },
    { id: 277, name: 'Blade Shield', tree: 'Traps' },
    { id: 278, name: 'Venom', tree: 'Shadow Disciplines' },
    { id: 279, name: 'Shadow Master', tree: 'Shadow Disciplines' },
    { id: 280, name: 'Phoenix Strike', tree: 'Martial Arts' },
  ],
};

const QUEST_NAMES = {
  0: 'Den of Evil', 1: 'Sisters\' Burial Grounds', 2: 'Tools of the Trade', 3: 'Search for Cain', 4: 'The Forgotten Tower', 5: 'Sisters to the Slaughter',
  6: 'Radament\'s Lair', 7: 'The Horadric Staff', 8: 'Tainted Sun', 9: 'Arcane Sanctuary', 10: 'The Summoner', 11: 'The Seven Tombs',
  12: 'Lam Esen\'s Tome', 13: 'Khalim\'s Will', 14: 'Blade of the Old Religion', 15: 'Golden Bird', 16: 'Gidbinn', 17: 'Mephisto',
  18: 'Izual', 19: 'Hell\'s Forge', 20: 'Diablo',
  21: 'Shenk the Overseer', 22: 'Rescue Barbarians', 23: 'Anya', 24: 'Nihlathak', 25: 'Ancients', 26: 'Baal'
};

const WAYPOINT_NAMES = [
  'Rogue Encampment', 'Cold Plains', 'Stony Field', 'Dark Wood', 'Black Marsh', 'Outer Cloister', 'Jail Lvl 1', 'Inner Cloister', 'Catacombs Lvl 2',
  'Lut Gholein', 'Sewers Lvl 2', 'Dry Hills', 'Halls of the Dead Lvl 2', 'Far Oasis', 'Lost City', 'Palace Cellar Lvl 1', 'Arcane Sanctuary', 'Canyon of the Magi',
  'Kurast Docks', 'Spider Forest', 'Great Marsh', 'Flayer Jungle', 'Lower Kurast', 'Kurast Bazaar', 'Upper Kurast', 'Travincal', 'Durance of Hate Lvl 2',
  'Pandemonium Fortress', 'City of the Damned', 'River of Flame',
  'Harrogath', 'Frigid Highlands', 'Arreat Plateau', 'Crystalline Passage', 'Halls of Pain', 'Glacial Trail', 'Frozen Tundra', 'Ancients\' Way', 'Worldstone Keep Lvl 2'
];

const EQUIPPED_SLOTS = {
  1: 'Helm', 2: 'Amulet', 3: 'Armor',
  4: 'Right Hand Weapon', 5: 'Shield / Offhand',
  6: 'Right Ring', 7: 'Left Ring',
  8: 'Belt', 9: 'Boots', 10: 'Gloves',
  11: 'Swap Weapon Right', 12: 'Swap Weapon Left'
};

const STORED_LOCATIONS = {
  1: 'Inventory', 4: 'Cube', 5: 'Stash'
};

const QUALITIES = {
  1: 'Inferior', 2: 'Normal', 3: 'Superior', 4: 'Magic',
  5: 'Set', 6: 'Rare', 7: 'Unique', 8: 'Crafted'
};

// Item Database (Code -> Name & Type)
const ITEM_DATABASE = {
  // Books & Containers & Utility
  'tbk': { name: 'Tome of Town Portal', type: 'Utility' },
  'ibk': { name: 'Tome of Identify', type: 'Utility' },
  'tsc': { name: 'Scroll of Town Portal', type: 'Consumable' },
  'isc': { name: 'Scroll of Identify', type: 'Consumable' },
  'box': { name: 'Horadric Cube', type: 'Quest / Container' },
  'key': { name: 'Key', type: 'Utility' },
  'aqv': { name: 'Quiver of Arrows', type: 'Ammunition' },
  'cqv': { name: 'Quiver of Bolts', type: 'Ammunition' },

  // Quest Items
  'qey': { name: 'Khalim\'s Eye', type: 'Quest Item' },
  'qbr': { name: 'Khalim\'s Brain', type: 'Quest Item' },
  'qhr': { name: 'Khalim\'s Heart', type: 'Quest Item' },
  'qfl': { name: 'Khalim\'s Flail', type: 'Quest Item' },
  'hst': { name: 'Horadric Staff', type: 'Quest Item' },

  // Charms
  'cm1': { name: 'Small Charm', type: 'Charm' },
  'cm2': { name: 'Large Charm', type: 'Charm' },
  'cm3': { name: 'Grand Charm', type: 'Charm' },

  // Jewelry
  'rin': { name: 'Ring', type: 'Ring' },
  'amu': { name: 'Amulet', type: 'Amulet' },

  // Armor & Clothing
  'cap': { name: 'Cap', type: 'Helm' },
  'fhl': { name: 'Full Helm', type: 'Helm' },
  'skp': { name: 'Skull Cap', type: 'Helm' },
  'hlm': { name: 'Helm', type: 'Helm' },
  'ghm': { name: 'Great Helm', type: 'Helm' },
  'bhm': { name: 'Bone Helm', type: 'Helm' },
  'xhl': { name: 'Basinet', type: 'Helm' },
  'dr3': { name: 'Antlers', type: 'Helm' },
  'lea': { name: 'Leather Armor', type: 'Body Armor' },
  'gth': { name: 'Gothic Plate', type: 'Body Armor' },
  'rng': { name: 'Ring Mail', type: 'Body Armor' },
  'spl': { name: 'Splint Mail', type: 'Body Armor' },
  'xcl': { name: 'Tigulated Mail', type: 'Body Armor' },
  'xla': { name: 'Demonhide Armor', type: 'Body Armor' },
  'mbl': { name: 'Belt', type: 'Belt' },
  'tbl': { name: 'Heavy Belt', type: 'Belt' },
  'vbl': { name: 'Light Belt', type: 'Belt' },
  'vbt': { name: 'Heavy Boots', type: 'Boots' },
  'tbt': { name: 'Light Plate Boots', type: 'Boots' },
  'lbt': { name: 'Leather Boots', type: 'Boots' },
  'mbt': { name: 'Chain Boots', type: 'Boots' },
  'xlb': { name: 'Demonhide Boots', type: 'Boots' },
  'xvb': { name: 'Sharkskin Boots', type: 'Boots' },
  'vgl': { name: 'Heavy Gloves', type: 'Gloves' },
  'lgl': { name: 'Leather Gloves', type: 'Gloves' },
  'hbl': { name: 'Girdle', type: 'Belt' },
  'lbl': { name: 'Sash', type: 'Belt' },
  'xrs': { name: 'Cuirass', type: 'Body Armor' },
  'bsh': { name: 'Bone Shield', type: 'Shield' },
  'pa1': { name: 'Targe', type: 'Shield' },

  // Weapons & Bows
  'hbw': { name: 'Hunter\'s Bow', type: 'Bow' },
  'sbw': { name: 'Short Bow', type: 'Bow' },
  'lbw': { name: 'Long Bow', type: 'Bow' },
  'swb': { name: 'Short War Bow', type: 'Bow' },
  'lwb': { name: 'Long War Bow', type: 'Bow' },
  'cbw': { name: 'Composite Bow', type: 'Bow' },
  'sbb': { name: 'Short Battle Bow', type: 'Bow' },
  'lbb': { name: 'Long Battle Bow', type: 'Bow' },
  '8lw': { name: 'Gothic Bow', type: 'Bow' },
  '8s8': { name: 'Short Siege Bow', type: 'Bow' },
  'am1': { name: 'Stag Bow', type: 'Amazon Bow' },
  'am2': { name: 'Reflex Bow', type: 'Amazon Bow' },
  'am3': { name: 'Maiden Spear', type: 'Amazon Spear' },
  'am6': { name: 'Ashwood Bow', type: 'Amazon Bow' },
  'am7': { name: 'Ceremonial Bow', type: 'Amazon Bow' },
  'crs': { name: 'Crystal Sword', type: 'Sword' },
  'hal': { name: 'Halberd', type: 'Polearm' },
  'lsd': { name: 'Long Sword', type: 'Sword' },
  'wsd': { name: 'War Sword', type: 'Sword' },
  'bwn': { name: 'Bone Wand', type: 'Wand' },

  // Runes (level = rune number, El lowest to Zod highest)
  'r01': { name: 'El Rune', type: 'Rune', level: 1 },
  'r02': { name: 'Eld Rune', type: 'Rune', level: 2 },
  'r03': { name: 'Tir Rune', type: 'Rune', level: 3 },
  'r04': { name: 'Nef Rune', type: 'Rune', level: 4 },
  'r05': { name: 'Eth Rune', type: 'Rune', level: 5 },
  'r06': { name: 'Ith Rune', type: 'Rune', level: 6 },
  'r07': { name: 'Tal Rune', type: 'Rune', level: 7 },
  'r08': { name: 'Ral Rune', type: 'Rune', level: 8 },
  'r09': { name: 'Ort Rune', type: 'Rune', level: 9 },
  'r10': { name: 'Thul Rune', type: 'Rune', level: 10 },
  'r11': { name: 'Amn Rune', type: 'Rune', level: 11 },
  'r12': { name: 'Sol Rune', type: 'Rune', level: 12 },
  'r13': { name: 'Shael Rune', type: 'Rune', level: 13 },
  'r14': { name: 'Dol Rune', type: 'Rune', level: 14 },
  'r15': { name: 'Hel Rune', type: 'Rune', level: 15 },
  'r16': { name: 'Io Rune', type: 'Rune', level: 16 },
  'r17': { name: 'Lum Rune', type: 'Rune', level: 17 },
  'r18': { name: 'Ko Rune', type: 'Rune', level: 18 },
  'r19': { name: 'Fal Rune', type: 'Rune', level: 19 },
  'r20': { name: 'Lem Rune', type: 'Rune', level: 20 },
  'r21': { name: 'Pul Rune', type: 'Rune', level: 21 },
  'r22': { name: 'Um Rune', type: 'Rune', level: 22 },
  'r23': { name: 'Mal Rune', type: 'Rune', level: 23 },
  'r24': { name: 'Ist Rune', type: 'Rune', level: 24 },
  'r25': { name: 'Gul Rune', type: 'Rune', level: 25 },
  'r26': { name: 'Vex Rune', type: 'Rune', level: 26 },
  'r27': { name: 'Ohm Rune', type: 'Rune', level: 27 },
  'r28': { name: 'Lo Rune', type: 'Rune', level: 28 },
  'r29': { name: 'Sur Rune', type: 'Rune', level: 29 },
  'r30': { name: 'Ber Rune', type: 'Rune', level: 30 },
  'r31': { name: 'Jah Rune', type: 'Rune', level: 31 },
  'r32': { name: 'Cham Rune', type: 'Rune', level: 32 },
  'r33': { name: 'Zod Rune', type: 'Rune', level: 33 },

  // Gems (g + quality[c=chipped,f=flawed,s=normal,l=flawless,p=perfect] + color)
  'gcv': { name: 'Chipped Amethyst', type: 'Gem' },
  'gfv': { name: 'Flawed Amethyst', type: 'Gem' },
  'gsv': { name: 'Amethyst', type: 'Gem' },
  'gzv': { name: 'Flawless Amethyst', type: 'Gem' },
  'gpv': { name: 'Perfect Amethyst', type: 'Gem' },
  'gcy': { name: 'Chipped Topaz', type: 'Gem' },
  'gfy': { name: 'Flawed Topaz', type: 'Gem' },
  'gsy': { name: 'Topaz', type: 'Gem' },
  'gly': { name: 'Flawless Topaz', type: 'Gem' },
  'gpy': { name: 'Perfect Topaz', type: 'Gem' },
  'gcb': { name: 'Chipped Sapphire', type: 'Gem' },
  'gfb': { name: 'Flawed Sapphire', type: 'Gem' },
  'gsb': { name: 'Sapphire', type: 'Gem' },
  'glb': { name: 'Flawless Sapphire', type: 'Gem' },
  'gpb': { name: 'Perfect Sapphire', type: 'Gem' },
  'gcg': { name: 'Chipped Emerald', type: 'Gem' },
  'gfg': { name: 'Flawed Emerald', type: 'Gem' },
  'gsg': { name: 'Emerald', type: 'Gem' },
  'glg': { name: 'Flawless Emerald', type: 'Gem' },
  'gpg': { name: 'Perfect Emerald', type: 'Gem' },
  'gcr': { name: 'Chipped Ruby', type: 'Gem' },
  'gfr': { name: 'Flawed Ruby', type: 'Gem' },
  'gsr': { name: 'Ruby', type: 'Gem' },
  'glr': { name: 'Flawless Ruby', type: 'Gem' },
  'gpr': { name: 'Perfect Ruby', type: 'Gem' },
  'gcw': { name: 'Chipped Diamond', type: 'Gem' },
  'gfw': { name: 'Flawed Diamond', type: 'Gem' },
  'gsw': { name: 'Diamond', type: 'Gem' },
  'glw': { name: 'Flawless Diamond', type: 'Gem' },
  'gpw': { name: 'Perfect Diamond', type: 'Gem' },
  'skc': { name: 'Chipped Skull', type: 'Gem' },
  'skf': { name: 'Flawed Skull', type: 'Gem' },
  'sku': { name: 'Skull', type: 'Gem' },
  'skl': { name: 'Flawless Skull', type: 'Gem' },
  'skz': { name: 'Perfect Skull', type: 'Gem' },
  'jew': { name: 'Jewel', type: 'Jewel' },

  // Potions
  'hp1': { name: 'Minor Healing Potion', type: 'Potion' },
  'hp2': { name: 'Light Healing Potion', type: 'Potion' },
  'hp3': { name: 'Healing Potion', type: 'Potion' },
  'hp4': { name: 'Greater Healing Potion', type: 'Potion' },
  'hp5': { name: 'Super Healing Potion', type: 'Potion' },
  'mp1': { name: 'Minor Mana Potion', type: 'Potion' },
  'mp2': { name: 'Light Mana Potion', type: 'Potion' },
  'mp3': { name: 'Mana Potion', type: 'Potion' },
  'mp4': { name: 'Greater Mana Potion', type: 'Potion' },
  'mp5': { name: 'Super Mana Potion', type: 'Potion' },
  'rvs': { name: 'Rejuvenation Potion', type: 'Potion' },
  'rvl': { name: 'Full Rejuvenation Potion', type: 'Potion' }
};

module.exports = {
  CLASSES,
  CLASS_SKILLS,
  QUEST_NAMES,
  WAYPOINT_NAMES,
  EQUIPPED_SLOTS,
  STORED_LOCATIONS,
  QUALITIES,
  ITEM_DATABASE
};
