/**
 * Unique Item Reference (Diablo II LoD)
 * Source: Diablo II UniqueItems.txt game data.
 * Array index corresponds to the in-game "unique ID" stored in a save
 * file for Unique-quality items (see itemParser.js / getUniqueName).
 *
 * IMPORTANT: this ID -> name mapping has only been verified to work for
 * Normal/Exceptional tier armor, weapons, and shields. Elite-tier items
 * (armor codes starting with "x", weapon codes starting with "8"/"9") and
 * all jewelry (rings/amulets) use a different, not-yet-decoded bit layout
 * -- getUniqueName() only returns a name when the code matches, so those
 * categories safely fall back to no match rather than a wrong name.
 */

const UNIQUE_ITEMS = [
  { name: 'The Gnasher', code: 'hax' },
  { name: 'Deathspade', code: 'axe' },
  { name: 'Bladebone', code: '2ax' },
  { name: 'Mindrend', code: 'mpi' },
  { name: 'Rakescar', code: 'wax' },
  { name: 'Fechmars Axe', code: 'lax' },
  { name: 'Goreshovel', code: 'bax' },
  { name: 'The Chieftan', code: 'btx' },
  { name: 'Brainhew', code: 'gax' },
  { name: 'The Humongous', code: 'gix' },
  { name: 'Iros Torch', code: 'wnd' },
  { name: 'Maelstromwrath', code: 'ywn' },
  { name: 'Gravenspine', code: 'bwn' },
  { name: 'Umes Lament', code: 'gwn' },
  { name: 'Felloak', code: 'clb' },
  { name: 'Knell Striker', code: 'scp' },
  { name: 'Rusthandle', code: 'gsc' },
  { name: 'Stormeye', code: 'wsp' },
  { name: 'Stoutnail', code: 'spc' },
  { name: 'Crushflange', code: 'mac' },
  { name: 'Bloodrise', code: 'mst' },
  { name: 'The Generals Tan Do Li Ga', code: 'fla' },
  { name: 'Ironstone', code: 'whm' },
  { name: 'Bonesob', code: 'mau' },
  { name: 'Steeldriver', code: 'gma' },
  { name: 'Rixots Keen', code: 'ssd' },
  { name: 'Blood Crescent', code: 'scm' },
  { name: 'Krintizs Skewer', code: 'sbr' },
  { name: 'Gleamscythe', code: 'flc' },
  { name: 'Azurewrath', code: 'crs' },
  { name: 'Griswolds Edge', code: 'bsd' },
  { name: 'Hellplague', code: 'lsd' },
  { name: 'Culwens Point', code: 'wsd' },
  { name: 'Shadowfang', code: '2hs' },
  { name: 'Soulflay', code: 'clm' },
  { name: 'Kinemils Awl', code: 'gis' },
  { name: 'Blacktongue', code: 'bsw' },
  { name: 'Ripsaw', code: 'flb' },
  { name: 'The Patriarch', code: 'gsd' },
  { name: 'Gull', code: 'dgr' },
  { name: 'The Diggler', code: 'dir' },
  { name: 'The Jade Tan Do', code: 'kri' },
  { name: 'Irices Shard', code: 'bld' },
  { name: 'The Dragon Chang', code: 'spr' },
  { name: 'Razortine', code: 'tri' },
  { name: 'Bloodthief', code: 'brn' },
  { name: 'Lance of Yaggai', code: 'spt' },
  { name: 'The Tannr Gorerod', code: 'pik' },
  { name: 'Dimoaks Hew', code: 'bar' },
  { name: 'Steelgoad', code: 'vou' },
  { name: 'Soul Harvest', code: 'scy' },
  { name: 'The Battlebranch', code: 'pax' },
  { name: 'Woestave', code: 'hal' },
  { name: 'The Grim Reaper', code: 'wsc' },
  { name: 'Bane Ash', code: 'sst' },
  { name: 'Serpent Lord', code: 'lst' },
  { name: 'Lazarus Spire', code: 'cst' },
  { name: 'The Salamander', code: 'bst' },
  { name: 'The Iron Jang Bong', code: 'wst' },
  { name: 'Pluckeye', code: 'sbw' },
  { name: 'Witherstring', code: 'hbw' },
  { name: 'Rimeraven', code: 'lbw' },
  { name: 'Piercerib', code: 'cbw' },
  { name: 'Pullspite', code: 'sbb' },
  { name: 'Wizendraw', code: 'lbb' },
  { name: 'Hellclap', code: 'swb' },
  { name: 'Blastbark', code: 'lwb' },
  { name: 'Leadcrow', code: 'lxb' },
  { name: 'Ichorsting', code: 'mxb' },
  { name: 'Hellcast', code: 'hxb' },
  { name: 'Doomspittle', code: 'rxb' },
  { name: 'War Bonnet', code: 'cap' },
  { name: 'Tarnhelm', code: 'skp' },
  { name: 'Coif of Glory', code: 'hlm' },
  { name: 'Duskdeep', code: 'fhl' },
  { name: 'Wormskull', code: 'bhm' },
  { name: 'Howltusk', code: 'ghm' },
  { name: 'Undead Crown', code: 'crn' },
  { name: 'The Face of Horror', code: 'msk' },
  { name: 'Greyform', code: 'qui' },
  { name: 'Blinkbats Form', code: 'lea' },
  { name: 'The Centurion', code: 'hla' },
  { name: 'Twitchthroe', code: 'stu' },
  { name: 'Darkglow', code: 'rng' },
  { name: 'Hawkmail', code: 'scl' },
  { name: 'Sparking Mail', code: 'chn' },
  { name: 'Venomsward', code: 'brs' },
  { name: 'Iceblink', code: 'spl' },
  { name: 'Boneflesh', code: 'plt' },
  { name: 'Rockfleece', code: 'fld' },
  { name: 'Rattlecage', code: 'gth' },
  { name: 'Goldskin', code: 'ful' },
  { name: 'Victors Silk', code: 'aar' },
  { name: 'Heavenly Garb', code: 'ltp' },
  { name: 'Pelta Lunata', code: 'buc' },
  { name: 'Umbral Disk', code: 'sml' },
  { name: 'Stormguild', code: 'lrg' },
  { name: 'Wall of the Eyeless', code: 'bsh' },
  { name: 'Swordback Hold', code: 'spk' },
  { name: 'Steelclash', code: 'kit' },
  { name: 'Bverrit Keep', code: 'tow' },
  { name: 'The Ward', code: 'gts' },
  { name: 'The Hand of Broc', code: 'lgl' },
  { name: 'Bloodfist', code: 'vgl' },
  { name: 'Chance Guards', code: 'mgl' },
  { name: 'Magefist', code: 'tgl' },
  { name: 'Frostburn', code: 'hgl' },
  { name: 'Hotspur', code: 'lbt' },
  { name: 'Gorefoot', code: 'vbt' },
  { name: 'Treads of Cthon', code: 'mbt' },
  { name: 'Goblin Toe', code: 'tbt' },
  { name: 'Tearhaunch', code: 'hbt' },
  { name: 'Lenyms Cord', code: 'lbl' },
  { name: 'Snakecord', code: 'vbl' },
  { name: 'Nightsmoke', code: 'mbl' },
  { name: 'Goldwrap', code: 'tbl' },
  { name: 'Bladebuckle', code: 'hbl' },
  { name: 'Nokozan Relic', code: 'amu' },
  { name: 'The Eye of Etlich', code: 'amu' },
  { name: 'The Mahim-Oak Curio', code: 'amu' },
  { name: 'Nagelring', code: 'rin' },
  { name: 'Manald Heal', code: 'rin' },
  { name: 'The Stone of Jordan', code: 'rin' },
  { name: 'Amulet of the Viper', code: 'vip' },
  { name: 'Staff of Kings', code: 'msf' },
  { name: 'Horadric Staff', code: 'hst' },
  { name: 'Hell Forge Hammer', code: 'hfh' },
  { name: 'KhalimFlail', code: 'qf1' },
  { name: 'SuperKhalimFlail', code: 'qf2' },
  { name: 'Expansion', code: '' },
  { name: 'Coldkill', code: '9ha' },
  { name: 'Butcher\'s Pupil', code: '9ax' },
  { name: 'Islestrike', code: '92a' },
  { name: 'Pompe\'s Wrath', code: '9mp' },
  { name: 'Guardian Naga', code: '9wa' },
  { name: 'Warlord\'s Trust', code: '9la' },
  { name: 'Spellsteel', code: '9ba' },
  { name: 'Stormrider', code: '9bt' },
  { name: 'Boneslayer Blade', code: '9ga' },
  { name: 'The Minataur', code: '9gi' },
  { name: 'Suicide Branch', code: '9wn' },
  { name: 'Carin Shard', code: '9yw' },
  { name: 'Arm of King Leoric', code: '9bw' },
  { name: 'Blackhand Key', code: '9gw' },
  { name: 'Dark Clan Crusher', code: '9cl' },
  { name: 'Zakarum\'s Hand', code: '9sc' },
  { name: 'The Fetid Sprinkler', code: '9qs' },
  { name: 'Hand of Blessed Light', code: '9ws' },
  { name: 'Fleshrender', code: '9sp' },
  { name: 'Sureshrill Frost', code: '9ma' },
  { name: 'Moonfall', code: '9mt' },
  { name: 'Baezil\'s Vortex', code: '9fl' },
  { name: 'Earthshaker', code: '9wh' },
  { name: 'Bloodtree Stump', code: '9m9' },
  { name: 'The Gavel of Pain', code: '9gm' },
  { name: 'Bloodletter', code: '9ss' },
  { name: 'Coldsteel Eye', code: '9sm' },
  { name: 'Hexfire', code: '9sb' },
  { name: 'Blade of Ali Baba', code: '9fc' },
  { name: 'Ginther\'s Rift', code: '9cr' },
  { name: 'Headstriker', code: '9bs' },
  { name: 'Plague Bearer', code: '9ls' },
  { name: 'The Atlantian', code: '9wd' },
  { name: 'Crainte Vomir', code: '92h' },
  { name: 'Bing Sz Wang', code: '9cm' },
  { name: 'The Vile Husk', code: '9gs' },
  { name: 'Cloudcrack', code: '9b9' },
  { name: 'Todesfaelle Flamme', code: '9fb' },
  { name: 'Swordguard', code: '9gd' },
  { name: 'Spineripper', code: '9dg' },
  { name: 'Heart Carver', code: '9di' },
  { name: 'Blackbog\'s Sharp', code: '9kr' },
  { name: 'Stormspike', code: '9bl' },
  { name: 'The Impaler', code: '9sr' },
  { name: 'Kelpie Snare', code: '9tr' },
  { name: 'Soulfeast Tine', code: '9br' },
  { name: 'Hone Sundan', code: '9st' },
  { name: 'Spire of Honor', code: '9p9' },
  { name: 'The Meat Scraper', code: '9b7' },
  { name: 'Blackleach Blade', code: '9vo' },
  { name: 'Athena\'s Wrath', code: '9s8' },
  { name: 'Pierre Tombale Couant', code: '9pa' },
  { name: 'Husoldal Evo', code: '9h9' },
  { name: 'Grim\'s Burning Dead', code: '9wc' },
  { name: 'Razorswitch', code: '8ss' },
  { name: 'Ribcracker', code: '8ls' },
  { name: 'Chromatic Ire', code: '8cs' },
  { name: 'Warpspear', code: '8bs' },
  { name: 'Skullcollector', code: '8ws' },
  { name: 'Skystrike', code: '8sb' },
  { name: 'Riphook', code: '8hb' },
  { name: 'Kuko Shakaku', code: '8lb' },
  { name: 'Endlesshail', code: '8cb' },
  { name: 'Witchwild String', code: '8s8' },
  { name: 'Cliffkiller', code: '8l8' },
  { name: 'Magewrath', code: '8sw' },
  { name: 'Godstrike Arch', code: '8lw' },
  { name: 'Langer Briser', code: '8lx' },
  { name: 'Pus Spiter', code: '8mx' },
  { name: 'Buriza-Do Kyanon', code: '8hx' },
  { name: 'Demon Machine', code: '8rx' },
  { name: 'Armor', code: '' },
  { name: 'Peasent Crown', code: 'xap' },
  { name: 'Rockstopper', code: 'xkp' },
  { name: 'Stealskull', code: 'xlm' },
  { name: 'Darksight Helm', code: 'xhl' },
  { name: 'Valkiry Wing', code: 'xhm' },
  { name: 'Crown of Thieves', code: 'xrn' },
  { name: 'Blackhorn\'s Face', code: 'xsk' },
  { name: 'Vampiregaze', code: 'xh9' },
  { name: 'The Spirit Shroud', code: 'xui' },
  { name: 'Skin of the Vipermagi', code: 'xea' },
  { name: 'Skin of the Flayed One', code: 'xla' },
  { name: 'Ironpelt', code: 'xtu' },
  { name: 'Spiritforge', code: 'xng' },
  { name: 'Crow Caw', code: 'xcl' },
  { name: 'Shaftstop', code: 'xhn' },
  { name: 'Duriel\'s Shell', code: 'xrs' },
  { name: 'Skullder\'s Ire', code: 'xpl' },
  { name: 'Guardian Angel', code: 'xlt' },
  { name: 'Toothrow', code: 'xld' },
  { name: 'Atma\'s Wail', code: 'xth' },
  { name: 'Black Hades', code: 'xul' },
  { name: 'Corpsemourn', code: 'xar' },
  { name: 'Que-Hegan\'s Wisdon', code: 'xtp' },
  { name: 'Visceratuant', code: 'xuc' },
  { name: 'Mosers Blessed Circle', code: 'xml' },
  { name: 'Stormchaser', code: 'xrg' },
  { name: 'Tiamat\'s Rebuke', code: 'xit' },
  { name: 'Kerke\'s Sanctuary', code: 'xow' },
  { name: 'Radament\'s Sphere', code: 'xts' },
  { name: 'Lidless Wall', code: 'xsh' },
  { name: 'Lance Guard', code: 'xpk' },
  { name: 'Venom Grip', code: 'xlg' },
  { name: 'Gravepalm', code: 'xvg' },
  { name: 'Ghoulhide', code: 'xmg' },
  { name: 'Lavagout', code: 'xtg' },
  { name: 'Hellmouth', code: 'xhg' },
  { name: 'Infernostride', code: 'xlb' },
  { name: 'Waterwalk', code: 'xvb' },
  { name: 'Silkweave', code: 'xmb' },
  { name: 'Wartraveler', code: 'xtb' },
  { name: 'Gorerider', code: 'xhb' },
  { name: 'String of Ears', code: 'zlb' },
  { name: 'Razortail', code: 'zvb' },
  { name: 'Gloomstrap', code: 'zmb' },
  { name: 'Snowclash', code: 'ztb' },
  { name: 'Thudergod\'s Vigor', code: 'zhb' },
  { name: 'Elite Uniques', code: '' },
  { name: 'Harlequin Crest', code: 'uap' },
  { name: 'Veil of Steel', code: 'uhm' },
  { name: 'The Gladiator\'s Bane', code: 'utu' },
  { name: 'Arkaine\'s Valor', code: 'upl' },
  { name: 'Blackoak Shield', code: 'uml' },
  { name: 'Stormshield', code: 'uit' },
  { name: 'Hellslayer', code: '7bt' },
  { name: 'Messerschmidt\'s Reaver', code: '7ga' },
  { name: 'Baranar\'s Star', code: '7mt' },
  { name: 'Schaefer\'s Hammer', code: '7wh' },
  { name: 'The Cranium Basher', code: '7gm' },
  { name: 'Lightsabre', code: '7cr' },
  { name: 'Doombringer', code: '7b7' },
  { name: 'The Grandfather', code: '7gd' },
  { name: 'Wizardspike', code: '7dg' },
  { name: 'Constricting Ring', code: 'rin' },
  { name: 'Stormspire', code: '7wc' },
  { name: 'Eaglehorn', code: '6l7' },
  { name: 'Windforce', code: '6lw' },
  { name: 'Rings', code: '' },
  { name: 'Bul Katho\'s Wedding Band', code: 'rin' },
  { name: 'The Cat\'s Eye', code: 'amu' },
  { name: 'The Rising Sun', code: 'amu' },
  { name: 'Crescent Moon', code: 'amu' },
  { name: 'Mara\'s Kaleidoscope', code: 'amu' },
  { name: 'Atma\'s Scarab', code: 'amu' },
  { name: 'Dwarf Star', code: 'rin' },
  { name: 'Raven Frost', code: 'rin' },
  { name: 'Highlord\'s Wrath', code: 'amu' },
  { name: 'Saracen\'s Chance', code: 'amu' },
  { name: 'Class Specific', code: '' },
  { name: 'Arreat\'s Face', code: 'baa' },
  { name: 'Homunculus', code: 'nea' },
  { name: 'Titan\'s Revenge', code: 'ama' },
  { name: 'Lycander\'s Aim', code: 'am7' },
  { name: 'Lycander\'s Flank', code: 'am9' },
  { name: 'The Oculus', code: 'oba' },
  { name: 'Herald of Zakarum', code: 'pa9' },
  { name: 'Cutthroat1', code: '9tw' },
  { name: 'Jalal\'s Mane', code: 'dra' },
  { name: 'The Scalper', code: '9ta' },
  { name: 'Bloodmoon', code: '7sb' },
  { name: 'Djinnslayer', code: '7sm' },
  { name: 'Deathbit', code: '9tk' },
  { name: 'Warshrike', code: '7bk' },
  { name: 'Gutsiphon', code: '6rx' },
  { name: 'Razoredge', code: '7ha' },
  { name: 'Gore Ripper', code: '' },
  { name: 'Demonlimb', code: '7sp' },
  { name: 'Steelshade', code: 'ulm' },
  { name: 'Tomb Reaver', code: '7pa' },
  { name: 'Deaths\'s Web', code: '7gw' },
  { name: 'Nature\'s Peace', code: 'rin' },
  { name: 'Azurewrath', code: '7cr' },
  { name: 'Seraph\'s Hymn', code: 'amu' },
  { name: 'Zakarum\'s Salvation', code: '' },
  { name: 'Fleshripper', code: '7kr' },
  { name: 'Odium', code: '' },
  { name: 'Horizon\'s Tornado', code: '7fl' },
  { name: 'Stone Crusher', code: '7wh' },
  { name: 'Jadetalon', code: '7wb' },
  { name: 'Shadowdancer', code: 'uhb' },
  { name: 'Cerebus', code: 'drb' },
  { name: 'Tyrael\'s Might', code: 'uar' },
  { name: 'Souldrain', code: 'umg' },
  { name: 'Runemaster', code: '72a' },
  { name: 'Deathcleaver', code: '7wa' },
  { name: 'Executioner\'s Justice', code: '7gi' },
  { name: 'Stoneraven', code: 'amd' },
  { name: 'Leviathan', code: 'uld' },
  { name: 'Larzuk\'s Champion', code: '' },
  { name: 'Wisp', code: 'rin' },
  { name: 'Gargoyle\'s Bite', code: '7ts' },
  { name: 'Lacerator', code: '7b8' },
  { name: 'Mang Song\'s Lesson', code: '6ws' },
  { name: 'Viperfork', code: '7br' },
  { name: 'Ethereal Edge', code: '7ba' },
  { name: 'Demonhorn\'s Edge', code: 'bad' },
  { name: 'The Reaper\'s Toll', code: '7s8' },
  { name: 'Spiritkeeper', code: 'drd' },
  { name: 'Hellrack', code: '6hx' },
  { name: 'Alma Negra', code: 'pac' },
  { name: 'Darkforge Spawn', code: 'nef' },
  { name: 'Widowmaker', code: '6sw' },
  { name: 'Bloodraven\'s Charge', code: 'amb' },
  { name: 'Ghostflame', code: '7bl' },
  { name: 'Shadowkiller', code: '7cs' },
  { name: 'Gimmershred', code: '7ta' },
  { name: 'Griffon\'s Eye', code: 'ci3' },
  { name: 'Windhammer', code: '7m7' },
  { name: 'Thunderstroke', code: 'amf' },
  { name: 'Giantmaimer', code: '' },
  { name: 'Demon\'s Arch', code: '7s7' },
  { name: 'Boneflame', code: 'nee' },
  { name: 'Steelpillar', code: '7p7' },
  { name: 'Nightwing\'s Veil', code: 'uhm' },
  { name: 'Crown of Ages', code: 'urn' },
  { name: 'Andariel\'s Visage', code: 'usk' },
  { name: 'Darkfear', code: 'ulm' },
  { name: 'Dragonscale', code: 'pae' },
  { name: 'Steel Carapice', code: 'uul' },
  { name: 'Medusa\'s Gaze', code: 'uow' },
  { name: 'Ravenlore', code: 'dre' },
  { name: 'Boneshade', code: '7bw' },
  { name: 'Nethercrow', code: '' },
  { name: 'Flamebellow', code: '7gs' },
  { name: 'Fathom', code: 'obf' },
  { name: 'Wolfhowl', code: 'bac' },
  { name: 'Spirit Ward', code: 'uts' },
  { name: 'Kira\'s Guardian', code: 'ci2' },
  { name: 'Ormus\' Robes', code: 'uui' },
  { name: 'Gheed\'s Fortune', code: 'cm3' },
  { name: 'Stormlash', code: '7fl' },
  { name: 'Halaberd\'s Reign', code: 'bae' },
  { name: 'Warriv\'s Warder', code: '' },
  { name: 'Spike Thorn', code: 'upk' },
  { name: 'Dracul\'s Grasp', code: 'uvg' },
  { name: 'Frostwind', code: '7ls' },
  { name: 'Templar\'s Might', code: 'uar' },
  { name: 'Eschuta\'s temper', code: 'obc' },
  { name: 'Firelizard\'s Talons', code: '7lw' },
  { name: 'Sandstorm Trek', code: 'uvb' },
  { name: 'Marrowwalk', code: 'umb' },
  { name: 'Heaven\'s Light', code: '7sc' },
  { name: 'Merman\'s Speed', code: '' },
  { name: 'Arachnid Mesh', code: 'ulc' },
  { name: 'Nosferatu\'s Coil', code: 'uvc' },
  { name: 'Metalgrid', code: 'amu' },
  { name: 'Verdugo\'s Hearty Cord', code: 'umc' },
  { name: 'Sigurd\'s Staunch', code: '' },
  { name: 'Carrion Wind', code: 'rin' },
  { name: 'Giantskull', code: 'uh9' },
  { name: 'Ironward', code: '7ws' },
  { name: 'Annihilus', code: 'cm1' },
  { name: 'Arioc\'s Needle', code: '7sr' },
  { name: 'Cranebeak', code: '7mp' },
  { name: 'Nord\'s Tenderizer', code: '7cl' },
  { name: 'Earthshifter', code: '7gm' },
  { name: 'Wraithflight', code: '7gl' },
  { name: 'Bonehew', code: '7o7' },
  { name: 'Ondal\'s Wisdom', code: '6cs' },
  { name: 'The Reedeemer', code: '7sc' },
  { name: 'Headhunter\'s Glory', code: 'ush' },
  { name: 'Steelrend', code: 'uhg' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Rainbow Facet', code: 'jew' },
  { name: 'Hellfire Torch', code: 'cm2' },
];

module.exports = { UNIQUE_ITEMS };